// ===========================================================
// HLS sources generated by ActiveCore framework
// Date: 2021-09-03 14:57:06
// Copyright Alexander Antonov <antonov.alex.alex@gmail.com>
// ===========================================================

#include <ap_int.h>
#include <hls_stream.h>
#include "riscv_2stage.hpp"

typedef struct {
	ap_uint<1> if_id;
	ap_uint<1> resp_done;
	ap_uint<32> rdata;
	ap_uint<1> rdreq_pending;
	ap_uint<1> tid;
} genmcopipe_handle_instr_mem_struct;

typedef struct {
	ap_uint<1> instr_req_done;
	genmcopipe_handle_instr_mem_struct genmcopipe_handle_instr_mem;
} genpstage_IFETCH_TRX_BUF_STRUCT;

typedef struct {
	ap_uint<1> if_id;
	ap_uint<1> resp_done;
	ap_uint<32> rdata;
	ap_uint<1> rdreq_pending;
	ap_uint<1> tid;
} genmcopipe_handle_data_mem_struct;

typedef struct {
	ap_uint<32> curinstr_addr;
	ap_uint<32> nextinstr_addr;
	ap_uint<1> irq_recv;
	ap_uint<8> irq_mcause;
	ap_uint<1> jump_req_done;
	ap_uint<1> data_req_done;
	genmcopipe_handle_data_mem_struct genmcopipe_handle_data_mem;
	genmcopipe_handle_instr_mem_struct genmcopipe_handle_instr_mem;
} genpstage_EXEC_TRX_BUF_STRUCT;

typedef struct {
	ap_uint<32> curinstr_addr;
	ap_uint<32> nextinstr_addr;
	ap_uint<1> instr_req_done;
	riscv_2stage_busreq_mem_struct instr_busreq;
} genpstage_IFETCH_TRX_LOCAL_STRUCT;

typedef struct {
	ap_uint<32> instr_code;
	ap_uint<7> opcode;
	ap_uint<1> alu_unsigned;
	ap_uint<5> rs1_addr;
	ap_uint<5> rs2_addr;
	ap_uint<5> rd_addr;
	ap_uint<3> funct3;
	ap_uint<7> funct7;
	ap_uint<5> shamt;
	ap_uint<4> pred;
	ap_uint<4> succ;
	ap_uint<12> csrnum;
	ap_uint<5> zimm;
	ap_uint<32> immediate_I;
	ap_uint<32> immediate_S;
	ap_uint<32> immediate_B;
	ap_uint<32> immediate_U;
	ap_uint<32> immediate_J;
	ap_uint<2> op1_source;
	ap_uint<1> rd_req;
	ap_uint<3> rd_source;
	ap_uint<32> immediate;
	ap_uint<2> op2_source;
	ap_uint<1> alu_req;
	ap_uint<4> alu_opcode;
	ap_uint<1> jump_req;
	ap_uint<1> jump_src;
	ap_uint<1> rs1_req;
	ap_uint<1> rs2_req;
	ap_uint<1> jump_req_cond;
	ap_uint<1> mem_req;
	ap_uint<1> mem_cmd;
	ap_uint<1> fencereq;
	ap_uint<1> ebreakreq;
	ap_uint<1> ecallreq;
	ap_uint<1> csrreq;
	ap_uint<4> mem_be;
	ap_uint<1> load_signext;
	ap_uint<1> mret_req;
	ap_uint<32> rs1_rdata;
	ap_uint<32> rs2_rdata;
	ap_uint<32> csr_rdata;
	ap_uint<32> alu_op1;
	ap_uint<32> alu_op2;
	ap_uint<33> alu_op1_wide;
	ap_uint<33> alu_op2_wide;
	ap_uint<8> irq_mcause;
	ap_uint<1> irq_recv;
	ap_uint<33> alu_result_wide;
	ap_uint<32> alu_result;
	ap_uint<1> alu_CF;
	ap_uint<1> alu_SF;
	ap_uint<1> alu_ZF;
	ap_uint<1> alu_OF;
	ap_uint<1> alu_overflow;
	ap_uint<32> rd_wdata;
	ap_uint<1> rd_rdy;
	ap_uint<32> curinstraddr_imm;
	ap_uint<32> jump_vector;
	ap_uint<32> mem_addr;
	ap_uint<32> mem_wdata;
	ap_uint<1> jump_req_done;
	riscv_2stage_busreq_mem_struct data_busreq;
	ap_uint<1> data_req_done;
	ap_uint<32> mem_rdata;
	ap_uint<32> curinstr_addr;
	ap_uint<32> nextinstr_addr;
} genpstage_EXEC_TRX_LOCAL_STRUCT;

ap_uint<32> genpsticky_glbl_pc;
ap_uint<32> genpsticky_glbl_regfile [32];
ap_uint<1> genpsticky_glbl_jump_req_cmd;
ap_uint<32> genpsticky_glbl_jump_vector_cmd;
ap_uint<8> genpsticky_glbl_CSR_MCAUSE;
ap_uint<1> genpsticky_glbl_MIRQEN;
ap_uint<32> genpsticky_glbl_MRETADDR;
ap_uint<1> genmcopipe_instr_mem_wr_done;
ap_uint<1> genmcopipe_instr_mem_rd_done;
ap_uint<1> genmcopipe_instr_mem_full_flag;
ap_uint<1> genmcopipe_instr_mem_empty_flag;
ap_uint<1> genmcopipe_instr_mem_wr_ptr;
ap_uint<1> genmcopipe_instr_mem_rd_ptr;
ap_uint<1> genmcopipe_data_mem_wr_done;
ap_uint<1> genmcopipe_data_mem_rd_done;
ap_uint<1> genmcopipe_data_mem_full_flag;
ap_uint<1> genmcopipe_data_mem_empty_flag;
ap_uint<1> genmcopipe_data_mem_wr_ptr;
ap_uint<1> genmcopipe_data_mem_rd_ptr;
genpstage_IFETCH_TRX_BUF_STRUCT genpstage_IFETCH_TRX_BUF [0:0];
ap_uint<1> genpstage_IFETCH_TRX_BUF_COUNTER;
ap_uint<1> genpstage_IFETCH_TRX_BUF_COUNTER_NEMPTY;
ap_uint<1> genpstage_IFETCH_TRX_BUF_COUNTER_FULL;
ap_uint<1> genpstage_IFETCH_genctrl_stalled_glbl;
genpstage_EXEC_TRX_BUF_STRUCT genpstage_EXEC_TRX_BUF [0:0];
ap_uint<1> genpstage_EXEC_TRX_BUF_COUNTER;
ap_uint<1> genpstage_EXEC_TRX_BUF_COUNTER_NEMPTY;
ap_uint<1> genpstage_EXEC_TRX_BUF_COUNTER_FULL;
ap_uint<1> genpstage_EXEC_genctrl_stalled_glbl;

void riscv_2stage(ap_uint<1> geninit, hls::stream<ap_uint<8> >& irq_fifo, hls::stream<ap_uint<32> >& genmcopipe_instr_mem_resp, hls::stream<ap_uint<32> >& genmcopipe_data_mem_resp, hls::stream<genpmodule_riscv_2stage_genmcopipe_instr_mem_genstruct_fifo_wdata>& genmcopipe_instr_mem_req, hls::stream<genpmodule_riscv_2stage_genmcopipe_data_mem_genstruct_fifo_wdata>& genmcopipe_data_mem_req) {


	ap_uint<1> genmcopipe_instr_mem_wr_ptr_next;
	ap_uint<1> genmcopipe_instr_mem_rd_ptr_next;
	ap_uint<1> genmcopipe_data_mem_wr_ptr_next;
	ap_uint<1> genmcopipe_data_mem_rd_ptr_next;
	ap_uint<1> genpstage_IFETCH_genpctrl_flushreq;
	genpstage_IFETCH_TRX_LOCAL_STRUCT genpstage_IFETCH_TRX_LOCAL;
	ap_uint<1> genpstage_IFETCH_genctrl_active;
	ap_uint<1> genpstage_IFETCH_genctrl_working;
	ap_uint<1> genpstage_IFETCH_genctrl_succ;
	ap_uint<1> genpstage_IFETCH_genctrl_occupied;
	ap_uint<1> genpstage_IFETCH_genctrl_rdy;
	ap_uint<1> genpstage_IFETCH_genctrl_new;
	ap_uint<1> genpstage_IFETCH_genctrl_finish;
	ap_uint<1> gen139_pipex_succreq;
	ap_uint<32> gen140_pipex_succbuf;
	ap_uint<1> genpstage_EXEC_genpctrl_flushreq;
	genpstage_EXEC_TRX_LOCAL_STRUCT genpstage_EXEC_TRX_LOCAL;
	ap_uint<1> genpstage_EXEC_genctrl_active;
	ap_uint<1> genpstage_EXEC_genctrl_working;
	ap_uint<1> genpstage_EXEC_genctrl_succ;
	ap_uint<1> genpstage_EXEC_genctrl_occupied;
	ap_uint<1> genpstage_EXEC_genctrl_rdy;
	ap_uint<1> genpstage_EXEC_genctrl_new;
	ap_uint<1> genpstage_EXEC_genctrl_finish;
	ap_uint<1> gen141_pipex_var;
	ap_uint<33> gen142_pipex_var;
	ap_uint<1> gen143_pipex_var;
	ap_uint<1> gen144_pipex_var;
	ap_uint<1> gen145_pipex_var;
	ap_uint<1> gen146_pipex_var;
	ap_uint<1> gen147_pipex_var;
	ap_uint<1> gen148_pipex_var;
	ap_uint<1> gen149_pipex_var;
	ap_uint<1> gen150_pipex_var;
	ap_uint<1> gen151_pipex_var;
	ap_uint<32> gen152_pipex_var;
	ap_uint<1> gen153_pipex_var;
	ap_uint<32> gen154_pipex_var;
	ap_uint<12> gen155_pipex_var;
	ap_uint<1> gen156_pipex_var;
	ap_uint<32> gen157_pipex_var;
	ap_uint<13> gen158_pipex_var;
	ap_uint<1> gen159_pipex_var;
	ap_uint<32> gen160_pipex_var;
	ap_uint<32> gen161_pipex_var;
	ap_uint<21> gen162_pipex_var;
	ap_uint<1> gen163_pipex_var;
	ap_uint<32> gen164_pipex_var;
	ap_uint<1> gen165_pipex_var;
	ap_uint<1> gen166_pipex_var;
	ap_uint<1> gen167_pipex_var;
	ap_uint<1> gen168_pipex_var;
	ap_uint<32> gen169_pipex_var;
	ap_uint<1> gen170_pipex_var;
	ap_uint<1> gen171_pipex_var;
	ap_uint<32> gen172_pipex_var;
	ap_uint<1> gen173_pipex_var;
	ap_uint<1> gen174_pipex_var;
	ap_uint<1> gen175_pipex_var;
	ap_uint<1> gen176_pipex_var;
	ap_uint<1> gen177_pipex_var;
	ap_uint<1> gen178_pipex_var;
	ap_uint<32> gen179_pipex_var;
	ap_uint<32> gen180_pipex_var;
	ap_uint<32> gen181_pipex_var;
	ap_uint<1> gen182_pipex_var;
	ap_uint<1> gen183_pipex_var;
	ap_uint<1> gen184_pipex_var;
	ap_uint<1> gen185_pipex_var;
	ap_uint<1> gen186_pipex_var;
	ap_uint<32> gen187_pipex_var [32];
	ap_uint<32> gen188_pipex_var [32];
	ap_uint<1> gen189_pipex_var;
	ap_uint<1> gen190_pipex_var;
	ap_uint<1> gen191_pipex_var;
	ap_uint<1> gen192_pipex_var;
	ap_uint<1> gen193_pipex_var;
	ap_uint<1> gen194_pipex_var;
	ap_uint<33> gen195_pipex_var;
	ap_uint<33> gen196_pipex_var;
	ap_uint<1> gen197_pipex_var;
	ap_uint<1> gen198_pipex_var;
	ap_uint<33> gen199_pipex_var;
	ap_uint<1> gen200_pipex_var;
	ap_uint<33> gen201_pipex_var;
	ap_uint<1> gen202_pipex_var;
	ap_uint<1> gen203_pipex_var;
	ap_uint<1> gen204_pipex_var;
	ap_uint<1> gen205_pipex_var;
	ap_uint<1> gen206_pipex_var;
	ap_uint<1> gen207_pipex_var;
	ap_uint<1> gen208_pipex_var;
	ap_uint<34> gen209_pipex_var;
	ap_uint<34> gen210_pipex_var;
	ap_uint<33> gen211_pipex_var;
	ap_uint<33> gen212_pipex_var;
	ap_uint<33> gen213_pipex_var;
	ap_uint<64> gen214_pipex_var;
	ap_uint<64> gen215_pipex_var;
	ap_uint<32> gen216_pipex_var;
	ap_uint<1> gen217_pipex_var;
	ap_uint<64> gen218_pipex_var;
	ap_uint<64> gen219_pipex_var;
	ap_uint<33> gen220_pipex_var;
	ap_uint<33> gen221_pipex_var;
	ap_uint<33> gen222_pipex_var;
	ap_uint<1> gen223_pipex_var;
	ap_uint<1> gen224_pipex_var;
	ap_uint<1> gen225_pipex_var;
	ap_uint<1> gen226_pipex_var;
	ap_uint<1> gen227_pipex_var;
	ap_uint<1> gen228_pipex_var;
	ap_uint<1> gen229_pipex_var;
	ap_uint<1> gen230_pipex_var;
	ap_uint<1> gen231_pipex_var;
	ap_uint<1> gen232_pipex_var;
	ap_uint<1> gen233_pipex_var;
	ap_uint<1> gen234_pipex_var;
	ap_uint<33> gen235_pipex_var;
	ap_uint<1> gen236_pipex_var;
	ap_uint<1> gen237_pipex_var;
	ap_uint<1> gen238_pipex_var;
	ap_uint<1> gen239_pipex_var;
	ap_uint<1> gen240_pipex_var;
	ap_uint<1> gen241_pipex_var;
	ap_uint<1> gen242_pipex_var;
	ap_uint<1> gen243_pipex_var;
	ap_uint<1> gen244_pipex_var;
	ap_uint<1> gen245_pipex_var;
	ap_uint<1> gen246_pipex_var;
	ap_uint<1> gen247_pipex_var;
	ap_uint<1> gen248_pipex_var;
	ap_uint<1> gen249_pipex_var;
	ap_uint<1> gen250_pipex_var;
	ap_uint<1> gen251_pipex_var;
	ap_uint<1> gen252_pipex_var;
	ap_uint<1> gen253_pipex_var;
	ap_uint<1> gen254_pipex_var;
	ap_uint<1> gen255_pipex_var;
	ap_uint<1> gen256_pipex_var;
	ap_uint<1> gen257_pipex_var;
	ap_uint<1> gen258_pipex_var;
	ap_uint<1> gen259_pipex_var;
	ap_uint<1> gen260_pipex_var;
	ap_uint<1> gen261_pipex_var;
	ap_uint<1> gen262_pipex_var;
	ap_uint<8> gen263_pipex_var;
	ap_uint<1> gen264_pipex_var;
	ap_uint<32> gen265_pipex_var;
	ap_uint<1> gen266_pipex_var;
	ap_uint<32> gen267_pipex_var;
	ap_uint<1> gen268_pipex_var;
	ap_uint<1> gen269_pipex_var;
	ap_uint<1> gen270_pipex_var;
	ap_uint<16> gen271_pipex_var;
	ap_uint<1> gen272_pipex_var;
	ap_uint<32> gen273_pipex_var;
	ap_uint<1> gen274_pipex_var;
	ap_uint<32> gen275_pipex_var;
	ap_uint<1> gen276_pipex_var;
	ap_uint<1> gen277_pipex_var;
	ap_uint<1> gen278_pipex_var;
	ap_uint<1> gen279_pipex_var;
	ap_uint<32> gen280_pipex_mcopipe_rdata;
	ap_uint<32> gen281_pipex_mcopipe_rdata;
	genpmodule_riscv_2stage_genmcopipe_data_mem_genstruct_fifo_wdata gen282_pipex_req_struct;
	ap_uint<32> gen283_pipex_mcopipe_rdata;
	genpmodule_riscv_2stage_genmcopipe_instr_mem_genstruct_fifo_wdata gen284_pipex_req_struct;
	genpstage_EXEC_TRX_BUF_STRUCT genpstage_EXEC_push_trx;
	ap_uint<1> gen148_cyclix_var;
	ap_uint<1> gen149_cyclix_var;
	ap_uint<1> gen150_cyclix_var;
	ap_uint<1> gen151_cyclix_var;
	ap_uint<1> gen152_cyclix_var;
	ap_uint<1> gen153_cyclix_var;
	ap_uint<1> gen154_cyclix_var;
	ap_uint<1> gen155_cyclix_var;
	ap_uint<1> gen156_cyclix_var;
	ap_uint<1> gen157_cyclix_var;
	ap_uint<1> gen158_cyclix_var;
	ap_uint<1> gen159_cyclix_var;
	ap_uint<1> gen160_cyclix_var;
	ap_uint<1> gen161_cyclix_var;
	ap_uint<1> gen162_cyclix_var;
	ap_uint<1> gen163_cyclix_var;
	ap_uint<1> gen164_cyclix_var;
	ap_uint<1> gen165_cyclix_var;
	ap_uint<1> gen166_cyclix_var;
	ap_uint<1> gen167_cyclix_var;
	ap_uint<1> gen168_cyclix_var;
	ap_uint<1> gen169_cyclix_var;
	ap_uint<1> gen170_cyclix_var;
	ap_uint<1> gen171_cyclix_var;
	ap_uint<1> gen172_cyclix_var;
	ap_uint<1> gen173_cyclix_var;
	ap_uint<1> gen174_cyclix_var;
	ap_uint<1> gen175_cyclix_var;
	ap_uint<1> gen176_cyclix_var;
	ap_uint<1> gen177_cyclix_var;
	ap_uint<1> gen178_cyclix_var;
	ap_uint<1> gen179_cyclix_var;
	ap_uint<1> gen180_cyclix_var;
	ap_uint<1> gen181_cyclix_var;
	ap_uint<32> gen182_cyclix_var [32];
	ap_uint<1> gen183_cyclix_var;
	ap_uint<1> gen184_cyclix_var;
	ap_uint<1> gen185_cyclix_var;
	ap_uint<1> gen186_cyclix_var;
	ap_uint<1> gen187_cyclix_var;
	ap_uint<1> gen188_cyclix_var;
	ap_uint<1> gen189_cyclix_var;
	ap_uint<1> gen190_cyclix_var;
	ap_uint<1> gen191_cyclix_var;
	ap_uint<1> gen192_cyclix_var;
	ap_uint<1> gen193_cyclix_var;
	ap_uint<1> gen194_cyclix_var;
	ap_uint<1> gen195_cyclix_var;
	ap_uint<1> gen196_cyclix_var;
	ap_uint<1> gen197_cyclix_var;
	ap_uint<1> gen198_cyclix_var;
	ap_uint<1> gen199_cyclix_var;
	ap_uint<1> gen200_cyclix_var;
	ap_uint<1> gen201_cyclix_var;
	ap_uint<1> gen202_cyclix_var;
	ap_uint<1> gen203_cyclix_var;
	ap_uint<1> gen204_cyclix_var;
	ap_uint<1> gen205_cyclix_var;
	ap_uint<1> gen206_cyclix_var;
	ap_uint<1> gen207_cyclix_var;
	ap_uint<1> gen208_cyclix_var;
	ap_uint<1> gen209_cyclix_var;
	ap_uint<1> gen210_cyclix_var;
	ap_uint<1> gen211_cyclix_var;
	ap_uint<1> gen212_cyclix_var;
	ap_uint<1> gen213_cyclix_var;
	ap_uint<1> gen214_cyclix_var;
	ap_uint<1> gen215_cyclix_var;
	ap_uint<1> gen216_cyclix_var;
	ap_uint<1> gen217_cyclix_var;
	ap_uint<1> gen218_cyclix_var;
	ap_uint<1> gen219_cyclix_var;
	ap_uint<1> gen220_cyclix_var;
	ap_uint<1> gen221_cyclix_var;
	ap_uint<1> gen222_cyclix_var;
	ap_uint<1> gen223_cyclix_var;
	ap_uint<1> gen224_cyclix_var;
	ap_uint<1> gen225_cyclix_var;
	ap_uint<1> gen226_cyclix_var;
	ap_uint<1> gen227_cyclix_var;
	ap_uint<1> gen228_cyclix_var;
	ap_uint<1> gen229_cyclix_var;
	ap_uint<1> gen230_cyclix_var;
	ap_uint<1> gen231_cyclix_var;
	ap_uint<1> gen232_cyclix_var;
	ap_uint<1> gen233_cyclix_var;
	ap_uint<1> gen234_cyclix_var;
	ap_uint<1> gen235_cyclix_var;
	ap_uint<1> gen236_cyclix_var;
	ap_uint<1> gen237_cyclix_var;
	ap_uint<1> gen238_cyclix_var;
	ap_uint<1> gen239_cyclix_var;
	ap_uint<1> gen240_cyclix_var;
	ap_uint<1> gen241_cyclix_var;
	ap_uint<1> gen242_cyclix_var;
	ap_uint<1> gen243_cyclix_var;
	ap_uint<1> gen244_cyclix_var;
	ap_uint<1> gen245_cyclix_var;
	ap_uint<1> gen246_cyclix_var;
	ap_uint<1> gen247_cyclix_var;
	ap_uint<1> gen248_cyclix_var;
	ap_uint<1> gen249_cyclix_var;
	ap_uint<1> gen250_cyclix_var;
	ap_uint<1> gen251_cyclix_var;
	ap_uint<1> gen252_cyclix_var;
	ap_uint<1> gen253_cyclix_var;
	ap_uint<1> gen254_cyclix_var;
	ap_uint<1> gen255_cyclix_var;
	ap_uint<1> gen256_cyclix_var;
	ap_uint<1> gen257_cyclix_var;
	ap_uint<1> gen258_cyclix_var;
	ap_uint<1> gen259_cyclix_var;
	ap_uint<1> gen260_cyclix_var;
	ap_uint<1> gen261_cyclix_var;
	ap_uint<1> gen262_cyclix_var;
	ap_uint<1> gen263_cyclix_var;
	ap_uint<1> gen264_cyclix_var;
	ap_uint<1> gen265_cyclix_var;
	ap_uint<1> gen266_cyclix_var;
	ap_uint<1> gen267_cyclix_var;
	ap_uint<1> gen268_cyclix_var;
	ap_uint<1> gen269_cyclix_var;
	ap_uint<1> gen270_cyclix_var;
	ap_uint<1> gen271_cyclix_var;
	ap_uint<1> gen272_cyclix_var;
	ap_uint<1> gen273_cyclix_var;
	ap_uint<1> gen274_cyclix_var;
	ap_uint<1> gen275_cyclix_var;
	ap_uint<1> gen276_cyclix_var;
	ap_uint<1> gen277_cyclix_var;
	ap_uint<1> gen278_cyclix_var;
	ap_uint<1> gen279_cyclix_var;
	ap_uint<1> gen280_cyclix_var;
	ap_uint<1> gen281_cyclix_var;
	ap_uint<1> gen282_cyclix_var;
	ap_uint<1> gen283_cyclix_var;
	ap_uint<1> gen284_cyclix_var;
	ap_uint<1> gen285_cyclix_var;
	ap_uint<1> gen286_cyclix_var;
	ap_uint<1> gen287_cyclix_var;
	ap_uint<1> gen288_cyclix_var;
	ap_uint<1> gen289_cyclix_var;
	ap_uint<1> gen290_cyclix_var;
	ap_uint<1> gen291_cyclix_var;
	ap_uint<1> gen292_cyclix_var;
	ap_uint<1> gen293_cyclix_var;
	ap_uint<1> gen294_cyclix_var;
	ap_uint<1> gen295_cyclix_var;

	if (geninit) {
		genpsticky_glbl_pc = ap_uint<32>(512);
		genpsticky_glbl_regfile[1] = ap_uint<32>(0);
		genpsticky_glbl_regfile[2] = ap_uint<32>(0);
		genpsticky_glbl_regfile[3] = ap_uint<32>(0);
		genpsticky_glbl_regfile[4] = ap_uint<32>(0);
		genpsticky_glbl_regfile[5] = ap_uint<32>(0);
		genpsticky_glbl_regfile[6] = ap_uint<32>(0);
		genpsticky_glbl_regfile[7] = ap_uint<32>(0);
		genpsticky_glbl_regfile[8] = ap_uint<32>(0);
		genpsticky_glbl_regfile[9] = ap_uint<32>(0);
		genpsticky_glbl_regfile[10] = ap_uint<32>(0);
		genpsticky_glbl_regfile[11] = ap_uint<32>(0);
		genpsticky_glbl_regfile[12] = ap_uint<32>(0);
		genpsticky_glbl_regfile[13] = ap_uint<32>(0);
		genpsticky_glbl_regfile[14] = ap_uint<32>(0);
		genpsticky_glbl_regfile[15] = ap_uint<32>(0);
		genpsticky_glbl_regfile[16] = ap_uint<32>(0);
		genpsticky_glbl_regfile[17] = ap_uint<32>(0);
		genpsticky_glbl_regfile[18] = ap_uint<32>(0);
		genpsticky_glbl_regfile[19] = ap_uint<32>(0);
		genpsticky_glbl_regfile[20] = ap_uint<32>(0);
		genpsticky_glbl_regfile[21] = ap_uint<32>(0);
		genpsticky_glbl_regfile[22] = ap_uint<32>(0);
		genpsticky_glbl_regfile[23] = ap_uint<32>(0);
		genpsticky_glbl_regfile[24] = ap_uint<32>(0);
		genpsticky_glbl_regfile[25] = ap_uint<32>(0);
		genpsticky_glbl_regfile[26] = ap_uint<32>(0);
		genpsticky_glbl_regfile[27] = ap_uint<32>(0);
		genpsticky_glbl_regfile[28] = ap_uint<32>(0);
		genpsticky_glbl_regfile[29] = ap_uint<32>(0);
		genpsticky_glbl_regfile[30] = ap_uint<32>(0);
		genpsticky_glbl_regfile[31] = ap_uint<32>(0);
		genpsticky_glbl_jump_req_cmd = ap_uint<32>(0);
		genpsticky_glbl_jump_vector_cmd = ap_uint<32>(0);
		genpsticky_glbl_CSR_MCAUSE = ap_uint<32>(0);
		genpsticky_glbl_MIRQEN = ap_uint<32>(1);
		genpsticky_glbl_MRETADDR = ap_uint<32>(0);
		genmcopipe_instr_mem_wr_done = ap_uint<32>(0);
		genmcopipe_instr_mem_rd_done = ap_uint<32>(0);
		genmcopipe_instr_mem_full_flag = ap_uint<32>(0);
		genmcopipe_instr_mem_empty_flag = ap_uint<32>(1);
		genmcopipe_instr_mem_wr_ptr = ap_uint<32>(0);
		genmcopipe_instr_mem_rd_ptr = ap_uint<32>(0);
		genmcopipe_data_mem_wr_done = ap_uint<32>(0);
		genmcopipe_data_mem_rd_done = ap_uint<32>(0);
		genmcopipe_data_mem_full_flag = ap_uint<32>(0);
		genmcopipe_data_mem_empty_flag = ap_uint<32>(1);
		genmcopipe_data_mem_wr_ptr = ap_uint<32>(0);
		genmcopipe_data_mem_rd_ptr = ap_uint<32>(0);
		genpstage_IFETCH_TRX_BUF = ap_uint<32>(0);
		genpstage_IFETCH_TRX_BUF_COUNTER = ap_uint<32>(0);
		genpstage_IFETCH_TRX_BUF_COUNTER_NEMPTY = ap_uint<32>(0);
		genpstage_IFETCH_TRX_BUF_COUNTER_FULL = ap_uint<32>(0);
		genpstage_IFETCH_genctrl_stalled_glbl = ap_uint<32>(0);
		genpstage_EXEC_TRX_BUF = ap_uint<32>(0);
		genpstage_EXEC_TRX_BUF_COUNTER = ap_uint<32>(0);
		genpstage_EXEC_TRX_BUF_COUNTER_NEMPTY = ap_uint<32>(0);
		genpstage_EXEC_TRX_BUF_COUNTER_FULL = ap_uint<32>(0);
		genpstage_EXEC_genctrl_stalled_glbl = ap_uint<32>(0);

	} else {
gen182_cyclix_var = genpsticky_glbl_regfile;
		// mcopipe processing
		genmcopipe_instr_mem_wr_done = ap_uint<32>(0);
		genmcopipe_instr_mem_rd_done = ap_uint<32>(0);
		genmcopipe_instr_mem_wr_ptr_next = (genmcopipe_instr_mem_wr_ptr + ap_uint<32>(1));
		genmcopipe_instr_mem_rd_ptr_next = (genmcopipe_instr_mem_rd_ptr + ap_uint<32>(1));
		genmcopipe_data_mem_wr_done = ap_uint<32>(0);
		genmcopipe_data_mem_rd_done = ap_uint<32>(0);
		genmcopipe_data_mem_wr_ptr_next = (genmcopipe_data_mem_wr_ptr + ap_uint<32>(1));
		genmcopipe_data_mem_rd_ptr_next = (genmcopipe_data_mem_rd_ptr + ap_uint<32>(1));
		// logic of stages
		// #### Stage processing: EXEC ####
		genpstage_EXEC_genctrl_succ = ap_uint<32>(0);
		genpstage_EXEC_genctrl_working = ap_uint<32>(0);
		gen148_cyclix_var = genpstage_EXEC_genctrl_stalled_glbl;
		if (gen148_cyclix_var) {
			genpstage_EXEC_genctrl_new = ap_uint<32>(0);
			genpstage_EXEC_genctrl_stalled_glbl = ap_uint<32>(0);
			genpstage_EXEC_genctrl_active = ap_uint<32>(1);
		}
		gen149_cyclix_var = ap_uint<1>(0);
		gen149_cyclix_var = (gen149_cyclix_var || gen148_cyclix_var);
		gen149_cyclix_var = !gen149_cyclix_var;
		if (gen149_cyclix_var) {
			genpstage_EXEC_genctrl_active = genpstage_EXEC_TRX_BUF_COUNTER_NEMPTY;
			genpstage_EXEC_genctrl_new = genpstage_EXEC_genctrl_active;
		}
		genpstage_EXEC_genctrl_occupied = genpstage_EXEC_genctrl_active;
		genpstage_EXEC_genctrl_finish = ap_uint<32>(0);
		genpstage_EXEC_genpctrl_flushreq = ap_uint<32>(0);
		gen150_cyclix_var = genpstage_EXEC_genctrl_occupied;
		if (gen150_cyclix_var) {
			// Initializing new newaccums descriptors ####
			gen151_cyclix_var = genpstage_EXEC_genctrl_new;
			if (gen151_cyclix_var) {
				genpstage_EXEC_TRX_BUF = ap_uint<32>(0);
				genpstage_EXEC_TRX_BUF = ap_uint<32>(0);
				genpstage_EXEC_TRX_BUF = ap_uint<32>(0);
				genpstage_EXEC_TRX_BUF = ap_uint<32>(0);
			}
			// Fetching locals from src_glbls
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_BUF[0].irq_mcause;
			genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_BUF[0].irq_recv;
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_BUF[0].jump_req_done;
			genpstage_EXEC_TRX_LOCAL = '{default:ap_uint<32>(0)};
			genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_BUF[0].data_req_done;
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_BUF[0].curinstr_addr;
			genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_BUF[0].nextinstr_addr;
			// Acquiring mcopipe rdata
			gen152_cyclix_var = genpstage_EXEC_TRX_BUF[0].genmcopipe_handle_data_mem.rdreq_pending;
			if (gen152_cyclix_var) {
				gen153_cyclix_var = (genpstage_EXEC_TRX_BUF[0].genmcopipe_handle_data_mem.if_id == ap_uint<1>(0));
				gen154_cyclix_var = gen153_cyclix_var;
				if (gen154_cyclix_var) {
					gen155_cyclix_var = (genpstage_EXEC_TRX_BUF[0].genmcopipe_handle_data_mem.tid == genmcopipe_data_mem_rd_ptr);
					gen156_cyclix_var = gen155_cyclix_var;
					if (gen156_cyclix_var) {
						gen157_cyclix_var = genmcopipe_data_mem_resp.read_nb(gen280_pipex_mcopipe_rdata);
						gen158_cyclix_var = gen157_cyclix_var;
						if (gen158_cyclix_var) {
							genpstage_EXEC_TRX_BUF = ap_uint<32>(0);
							genpstage_EXEC_TRX_BUF = ap_uint<32>(1);
							genpstage_EXEC_TRX_BUF = gen280_pipex_mcopipe_rdata;
							genmcopipe_data_mem_rd_done = ap_uint<32>(1);
						}
					}
				}
			}
			gen159_cyclix_var = genpstage_EXEC_TRX_BUF[0].genmcopipe_handle_instr_mem.rdreq_pending;
			if (gen159_cyclix_var) {
				gen160_cyclix_var = (genpstage_EXEC_TRX_BUF[0].genmcopipe_handle_instr_mem.if_id == ap_uint<1>(0));
				gen161_cyclix_var = gen160_cyclix_var;
				if (gen161_cyclix_var) {
					gen162_cyclix_var = (genpstage_EXEC_TRX_BUF[0].genmcopipe_handle_instr_mem.tid == genmcopipe_instr_mem_rd_ptr);
					gen163_cyclix_var = gen162_cyclix_var;
					if (gen163_cyclix_var) {
						gen164_cyclix_var = genmcopipe_instr_mem_resp.read_nb(gen281_pipex_mcopipe_rdata);
						gen165_cyclix_var = gen164_cyclix_var;
						if (gen165_cyclix_var) {
							genpstage_EXEC_TRX_BUF = ap_uint<32>(0);
							genpstage_EXEC_TRX_BUF = ap_uint<32>(1);
							genpstage_EXEC_TRX_BUF = gen281_pipex_mcopipe_rdata;
							genmcopipe_instr_mem_rd_done = ap_uint<32>(1);
						}
					}
				}
			}
			// Pipeline flush processing
			gen166_cyclix_var = genpstage_EXEC_genpctrl_flushreq;
			if (gen166_cyclix_var) {
				genpstage_EXEC_genctrl_active = ap_uint<32>(0);
			}
		}
		// Saving succ targets
		// Generating payload
		gen167_cyclix_var = genpstage_EXEC_TRX_BUF[0].genmcopipe_handle_instr_mem.resp_done;
		if (gen167_cyclix_var) {
			genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_BUF[0].genmcopipe_handle_instr_mem.rdata;
		}
		gen149_pipex_var = genpstage_EXEC_TRX_BUF[0].genmcopipe_handle_instr_mem.resp_done;
		gen150_pipex_var = ~gen149_pipex_var;
		gen151_pipex_var = gen150_pipex_var;
		gen168_cyclix_var = gen151_pipex_var;
		if (gen168_cyclix_var) {
			gen169_cyclix_var = genpstage_EXEC_genctrl_active;
			if (gen169_cyclix_var) {
				genpstage_EXEC_genctrl_stalled_glbl = ap_uint<32>(1);
			}
			genpstage_EXEC_genctrl_active = ap_uint<32>(0);
		}
		genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.instr_code[6:0];
		genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
		genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.instr_code[19:15];
		genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.instr_code[24:20];
		genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.instr_code[11:7];
		genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.instr_code[14:12];
		genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.instr_code[31:25];
		genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.instr_code[24:20];
		genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.instr_code[27:24];
		genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.instr_code[23:20];
		genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.instr_code[31:20];
		genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.instr_code[19:15];
		gen152_pipex_var = genpstage_EXEC_TRX_LOCAL.instr_code[31:20];
		gen153_pipex_var = gen152_pipex_var[31];
		gen154_pipex_var = gen153_pipex_var.concat((ap_uint<31>)gen153_pipex_var.concat((ap_uint<30>)gen153_pipex_var.concat((ap_uint<29>)gen153_pipex_var.concat((ap_uint<28>)gen153_pipex_var.concat((ap_uint<27>)gen153_pipex_var.concat((ap_uint<26>)gen153_pipex_var.concat((ap_uint<25>)gen153_pipex_var.concat((ap_uint<24>)gen153_pipex_var.concat((ap_uint<23>)gen153_pipex_var.concat((ap_uint<22>)gen153_pipex_var.concat((ap_uint<21>)gen153_pipex_var.concat((ap_uint<20>)gen153_pipex_var.concat((ap_uint<19>)gen153_pipex_var.concat((ap_uint<18>)gen153_pipex_var.concat((ap_uint<17>)gen153_pipex_var.concat((ap_uint<16>)gen153_pipex_var.concat((ap_uint<15>)gen153_pipex_var.concat((ap_uint<14>)gen153_pipex_var.concat((ap_uint<13>)gen153_pipex_var.concat((ap_uint<12>)genpstage_EXEC_TRX_LOCAL.instr_code[31:20]))))))))))))))))))));
		genpstage_EXEC_TRX_LOCAL = gen154_pipex_var;
		gen155_pipex_var = genpstage_EXEC_TRX_LOCAL.instr_code[31:25].concat((ap_uint<5>)genpstage_EXEC_TRX_LOCAL.instr_code[11:7]);
		gen156_pipex_var = gen155_pipex_var[11];
		gen157_pipex_var = gen156_pipex_var.concat((ap_uint<31>)gen156_pipex_var.concat((ap_uint<30>)gen156_pipex_var.concat((ap_uint<29>)gen156_pipex_var.concat((ap_uint<28>)gen156_pipex_var.concat((ap_uint<27>)gen156_pipex_var.concat((ap_uint<26>)gen156_pipex_var.concat((ap_uint<25>)gen156_pipex_var.concat((ap_uint<24>)gen156_pipex_var.concat((ap_uint<23>)gen156_pipex_var.concat((ap_uint<22>)gen156_pipex_var.concat((ap_uint<21>)gen156_pipex_var.concat((ap_uint<20>)gen156_pipex_var.concat((ap_uint<19>)gen156_pipex_var.concat((ap_uint<18>)gen156_pipex_var.concat((ap_uint<17>)gen156_pipex_var.concat((ap_uint<16>)gen156_pipex_var.concat((ap_uint<15>)gen156_pipex_var.concat((ap_uint<14>)gen156_pipex_var.concat((ap_uint<13>)gen156_pipex_var.concat((ap_uint<12>)gen155_pipex_var))))))))))))))))))));
		genpstage_EXEC_TRX_LOCAL = gen157_pipex_var;
		gen158_pipex_var = genpstage_EXEC_TRX_LOCAL.instr_code[31].concat((ap_uint<12>)genpstage_EXEC_TRX_LOCAL.instr_code[7].concat((ap_uint<11>)genpstage_EXEC_TRX_LOCAL.instr_code[30:25].concat((ap_uint<5>)genpstage_EXEC_TRX_LOCAL.instr_code[11:8].concat((ap_uint<1>)ap_uint<1>(0)))));
		gen159_pipex_var = gen158_pipex_var[12];
		gen160_pipex_var = gen159_pipex_var.concat((ap_uint<31>)gen159_pipex_var.concat((ap_uint<30>)gen159_pipex_var.concat((ap_uint<29>)gen159_pipex_var.concat((ap_uint<28>)gen159_pipex_var.concat((ap_uint<27>)gen159_pipex_var.concat((ap_uint<26>)gen159_pipex_var.concat((ap_uint<25>)gen159_pipex_var.concat((ap_uint<24>)gen159_pipex_var.concat((ap_uint<23>)gen159_pipex_var.concat((ap_uint<22>)gen159_pipex_var.concat((ap_uint<21>)gen159_pipex_var.concat((ap_uint<20>)gen159_pipex_var.concat((ap_uint<19>)gen159_pipex_var.concat((ap_uint<18>)gen159_pipex_var.concat((ap_uint<17>)gen159_pipex_var.concat((ap_uint<16>)gen159_pipex_var.concat((ap_uint<15>)gen159_pipex_var.concat((ap_uint<14>)gen159_pipex_var.concat((ap_uint<13>)gen158_pipex_var)))))))))))))))))));
		genpstage_EXEC_TRX_LOCAL = gen160_pipex_var;
		gen161_pipex_var = genpstage_EXEC_TRX_LOCAL.instr_code[31:12].concat((ap_uint<12>)ap_uint<12>(0));
		genpstage_EXEC_TRX_LOCAL = gen161_pipex_var;
		gen162_pipex_var = genpstage_EXEC_TRX_LOCAL.instr_code[31].concat((ap_uint<20>)genpstage_EXEC_TRX_LOCAL.instr_code[19:12].concat((ap_uint<12>)genpstage_EXEC_TRX_LOCAL.instr_code[20].concat((ap_uint<11>)genpstage_EXEC_TRX_LOCAL.instr_code[30:21].concat((ap_uint<1>)ap_uint<1>(0)))));
		gen163_pipex_var = gen162_pipex_var[20];
		gen164_pipex_var = gen163_pipex_var.concat((ap_uint<31>)gen163_pipex_var.concat((ap_uint<30>)gen163_pipex_var.concat((ap_uint<29>)gen163_pipex_var.concat((ap_uint<28>)gen163_pipex_var.concat((ap_uint<27>)gen163_pipex_var.concat((ap_uint<26>)gen163_pipex_var.concat((ap_uint<25>)gen163_pipex_var.concat((ap_uint<24>)gen163_pipex_var.concat((ap_uint<23>)gen163_pipex_var.concat((ap_uint<22>)gen163_pipex_var.concat((ap_uint<21>)gen162_pipex_var)))))))))));
		genpstage_EXEC_TRX_LOCAL = gen164_pipex_var;
		switch (genpstage_EXEC_TRX_LOCAL) {
			case 55:
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
				genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.immediate_U;
				break;
			case 23:
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(2);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.immediate_U;
				break;
			case 111:
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(2);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(4);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.immediate_J;
				break;
			case 103:
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(4);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.immediate_I;
				break;
			case 99:
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.immediate_B;
				gen165_pipex_var = (genpstage_EXEC_TRX_LOCAL.funct3 == ap_uint<32>(6));
				gen166_pipex_var = (genpstage_EXEC_TRX_LOCAL.funct3 == ap_uint<32>(7));
				gen167_pipex_var = (gen165_pipex_var | gen166_pipex_var);
				gen168_pipex_var = gen167_pipex_var;
				gen170_cyclix_var = gen168_pipex_var;
				if (gen170_cyclix_var) {
					genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				}
				break;
			case 3:
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(5);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
				genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.immediate_I;
				break;
			case 35:
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.immediate_S;
				break;
			case 19:
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.immediate_I;
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				switch (genpstage_EXEC_TRX_LOCAL) {
					case 0:
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						break;
					case 1:
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(4);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						gen169_pipex_var = ap_uint<27>(0).concat((ap_uint<5>)genpstage_EXEC_TRX_LOCAL.instr_code[24:20]);
						genpstage_EXEC_TRX_LOCAL = gen169_pipex_var;
						break;
					case 2:
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(2);
						break;
					case 3:
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(2);
						break;
					case 4:
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(7);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						break;
					case 5:
						gen170_pipex_var = genpstage_EXEC_TRX_LOCAL.instr_code[30];
						gen171_cyclix_var = gen170_pipex_var;
						if (gen171_cyclix_var) {
							genpstage_EXEC_TRX_LOCAL = ap_uint<32>(6);
						}
						gen171_pipex_var = ap_uint<1>(0);
						gen171_pipex_var = (gen171_pipex_var || gen170_pipex_var);
						gen171_pipex_var = !gen171_pipex_var;
						gen172_cyclix_var = gen171_pipex_var;
						if (gen172_cyclix_var) {
							genpstage_EXEC_TRX_LOCAL = ap_uint<32>(5);
						}
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						gen172_pipex_var = ap_uint<27>(0).concat((ap_uint<5>)genpstage_EXEC_TRX_LOCAL.instr_code[24:20]);
						genpstage_EXEC_TRX_LOCAL = gen172_pipex_var;
						break;
					case 6:
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(3);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						break;
					case 7:
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(2);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						break;
				}
				break;
			case 51:
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				switch (genpstage_EXEC_TRX_LOCAL) {
					case 0:
						gen173_pipex_var = genpstage_EXEC_TRX_LOCAL.instr_code[30];
						gen173_cyclix_var = gen173_pipex_var;
						if (gen173_cyclix_var) {
							genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						}
						gen174_pipex_var = ap_uint<1>(0);
						gen174_pipex_var = (gen174_pipex_var || gen173_pipex_var);
						gen174_pipex_var = !gen174_pipex_var;
						gen174_cyclix_var = gen174_pipex_var;
						if (gen174_cyclix_var) {
							genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
						}
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						break;
					case 1:
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(4);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						break;
					case 2:
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(2);
						break;
					case 3:
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(2);
						break;
					case 4:
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(7);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						break;
					case 5:
						gen175_pipex_var = genpstage_EXEC_TRX_LOCAL.instr_code[30];
						gen175_cyclix_var = gen175_pipex_var;
						if (gen175_cyclix_var) {
							genpstage_EXEC_TRX_LOCAL = ap_uint<32>(6);
						}
						gen176_pipex_var = ap_uint<1>(0);
						gen176_pipex_var = (gen176_pipex_var || gen175_pipex_var);
						gen176_pipex_var = !gen176_pipex_var;
						gen176_cyclix_var = gen176_pipex_var;
						if (gen176_cyclix_var) {
							genpstage_EXEC_TRX_LOCAL = ap_uint<32>(5);
						}
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						break;
					case 6:
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(3);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						break;
					case 7:
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(2);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						break;
				}
				break;
			case 15:
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				break;
			case 115:
				switch (genpstage_EXEC_TRX_LOCAL) {
					case 0:
						gen177_pipex_var = genpstage_EXEC_TRX_LOCAL.instr_code[20];
						gen177_cyclix_var = gen177_pipex_var;
						if (gen177_cyclix_var) {
							genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						}
						gen178_pipex_var = ap_uint<1>(0);
						gen178_pipex_var = (gen178_pipex_var || gen177_pipex_var);
						gen178_pipex_var = !gen178_pipex_var;
						gen178_cyclix_var = gen178_pipex_var;
						if (gen178_cyclix_var) {
							genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						}
						break;
					case 1:
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(6);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(2);
						break;
					case 2:
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(6);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(3);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(2);
						break;
					case 3:
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(6);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(8);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(2);
						break;
					case 5:
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(2);
						gen179_pipex_var = ap_uint<27>(0).concat((ap_uint<5>)genpstage_EXEC_TRX_LOCAL.zimm);
						genpstage_EXEC_TRX_LOCAL = gen179_pipex_var;
						break;
					case 6:
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(6);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(8);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(2);
						gen180_pipex_var = ap_uint<27>(0).concat((ap_uint<5>)genpstage_EXEC_TRX_LOCAL.zimm);
						genpstage_EXEC_TRX_LOCAL = gen180_pipex_var;
						break;
					case 7:
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(6);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(8);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(2);
						gen181_pipex_var = ap_uint<27>(0).concat((ap_uint<5>)genpstage_EXEC_TRX_LOCAL.zimm);
						genpstage_EXEC_TRX_LOCAL = gen181_pipex_var;
						break;
				}
				break;
		}
		gen182_pipex_var = genpstage_EXEC_TRX_LOCAL.mem_req;
		gen179_cyclix_var = gen182_pipex_var;
		if (gen179_cyclix_var) {
			switch (genpstage_EXEC_TRX_LOCAL) {
				case 0:
					genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
					genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
					break;
				case 1:
					genpstage_EXEC_TRX_LOCAL = ap_uint<32>(3);
					genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
					break;
				case 2:
					genpstage_EXEC_TRX_LOCAL = ap_uint<32>(15);
					break;
				case 4:
					genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
					break;
				case 5:
					genpstage_EXEC_TRX_LOCAL = ap_uint<32>(3);
					break;
			}
		}
		gen183_pipex_var = (genpstage_EXEC_TRX_LOCAL.instr_code == ap_uint<32>(807403635));
		gen184_pipex_var = gen183_pipex_var;
		gen180_cyclix_var = gen184_pipex_var;
		if (gen180_cyclix_var) {
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = genpsticky_glbl_MRETADDR;
		}
		gen185_pipex_var = (genpstage_EXEC_TRX_LOCAL.rd_addr == ap_uint<32>(0));
		gen186_pipex_var = gen185_pipex_var;
		gen181_cyclix_var = gen186_pipex_var;
		if (gen181_cyclix_var) {
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
		}
		gen187_pipex_var = gen34_cyclix_readPrev[1];
		gen187_pipex_var = gen34_cyclix_readPrev[2];
		gen187_pipex_var = gen34_cyclix_readPrev[3];
		gen187_pipex_var = gen34_cyclix_readPrev[4];
		gen187_pipex_var = gen34_cyclix_readPrev[5];
		gen187_pipex_var = gen34_cyclix_readPrev[6];
		gen187_pipex_var = gen34_cyclix_readPrev[7];
		gen187_pipex_var = gen34_cyclix_readPrev[8];
		gen187_pipex_var = gen34_cyclix_readPrev[9];
		gen187_pipex_var = gen34_cyclix_readPrev[10];
		gen187_pipex_var = gen34_cyclix_readPrev[11];
		gen187_pipex_var = gen34_cyclix_readPrev[12];
		gen187_pipex_var = gen34_cyclix_readPrev[13];
		gen187_pipex_var = gen34_cyclix_readPrev[14];
		gen187_pipex_var = gen34_cyclix_readPrev[15];
		gen187_pipex_var = gen34_cyclix_readPrev[16];
		gen187_pipex_var = gen34_cyclix_readPrev[17];
		gen187_pipex_var = gen34_cyclix_readPrev[18];
		gen187_pipex_var = gen34_cyclix_readPrev[19];
		gen187_pipex_var = gen34_cyclix_readPrev[20];
		gen187_pipex_var = gen34_cyclix_readPrev[21];
		gen187_pipex_var = gen34_cyclix_readPrev[22];
		gen187_pipex_var = gen34_cyclix_readPrev[23];
		gen187_pipex_var = gen34_cyclix_readPrev[24];
		gen187_pipex_var = gen34_cyclix_readPrev[25];
		gen187_pipex_var = gen34_cyclix_readPrev[26];
		gen187_pipex_var = gen34_cyclix_readPrev[27];
		gen187_pipex_var = gen34_cyclix_readPrev[28];
		gen187_pipex_var = gen34_cyclix_readPrev[29];
		gen187_pipex_var = gen34_cyclix_readPrev[30];
		gen187_pipex_var = gen34_cyclix_readPrev[31];
		genpstage_EXEC_TRX_LOCAL = gen187_pipex_var[genpstage_EXEC_TRX_LOCAL.rs1_addr];
		gen188_pipex_var = gen34_cyclix_readPrev[1];
		gen188_pipex_var = gen34_cyclix_readPrev[2];
		gen188_pipex_var = gen34_cyclix_readPrev[3];
		gen188_pipex_var = gen34_cyclix_readPrev[4];
		gen188_pipex_var = gen34_cyclix_readPrev[5];
		gen188_pipex_var = gen34_cyclix_readPrev[6];
		gen188_pipex_var = gen34_cyclix_readPrev[7];
		gen188_pipex_var = gen34_cyclix_readPrev[8];
		gen188_pipex_var = gen34_cyclix_readPrev[9];
		gen188_pipex_var = gen34_cyclix_readPrev[10];
		gen188_pipex_var = gen34_cyclix_readPrev[11];
		gen188_pipex_var = gen34_cyclix_readPrev[12];
		gen188_pipex_var = gen34_cyclix_readPrev[13];
		gen188_pipex_var = gen34_cyclix_readPrev[14];
		gen188_pipex_var = gen34_cyclix_readPrev[15];
		gen188_pipex_var = gen34_cyclix_readPrev[16];
		gen188_pipex_var = gen34_cyclix_readPrev[17];
		gen188_pipex_var = gen34_cyclix_readPrev[18];
		gen188_pipex_var = gen34_cyclix_readPrev[19];
		gen188_pipex_var = gen34_cyclix_readPrev[20];
		gen188_pipex_var = gen34_cyclix_readPrev[21];
		gen188_pipex_var = gen34_cyclix_readPrev[22];
		gen188_pipex_var = gen34_cyclix_readPrev[23];
		gen188_pipex_var = gen34_cyclix_readPrev[24];
		gen188_pipex_var = gen34_cyclix_readPrev[25];
		gen188_pipex_var = gen34_cyclix_readPrev[26];
		gen188_pipex_var = gen34_cyclix_readPrev[27];
		gen188_pipex_var = gen34_cyclix_readPrev[28];
		gen188_pipex_var = gen34_cyclix_readPrev[29];
		gen188_pipex_var = gen34_cyclix_readPrev[30];
		gen188_pipex_var = gen34_cyclix_readPrev[31];
		genpstage_EXEC_TRX_LOCAL = gen188_pipex_var[genpstage_EXEC_TRX_LOCAL.rs2_addr];
		gen189_pipex_var = (genpstage_EXEC_TRX_LOCAL.rs1_addr == ap_uint<32>(0));
		gen190_pipex_var = gen189_pipex_var;
		gen183_cyclix_var = gen190_pipex_var;
		if (gen183_cyclix_var) {
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
		}
		gen191_pipex_var = (genpstage_EXEC_TRX_LOCAL.rs2_addr == ap_uint<32>(0));
		gen192_pipex_var = gen191_pipex_var;
		gen184_cyclix_var = gen192_pipex_var;
		if (gen184_cyclix_var) {
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
		}
		gen193_pipex_var = genpstage_EXEC_TRX_LOCAL.csrreq;
		gen185_cyclix_var = gen193_pipex_var;
		if (gen185_cyclix_var) {
			genpstage_EXEC_TRX_LOCAL = genpsticky_glbl_CSR_MCAUSE;
		}
		genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.rs1_rdata;
		switch (genpstage_EXEC_TRX_LOCAL) {
			case 1:
				genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.immediate;
				break;
			case 2:
				genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.curinstr_addr;
				break;
		}
		genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.rs2_rdata;
		switch (genpstage_EXEC_TRX_LOCAL) {
			case 1:
				genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.immediate;
				break;
			case 2:
				genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.csr_rdata;
				break;
		}
		gen194_pipex_var = genpstage_EXEC_TRX_LOCAL.alu_unsigned;
		gen186_cyclix_var = gen194_pipex_var;
		if (gen186_cyclix_var) {
			gen195_pipex_var = ap_uint<1>(0).concat((ap_uint<32>)genpstage_EXEC_TRX_LOCAL.alu_op1);
			genpstage_EXEC_TRX_LOCAL = gen195_pipex_var;
			gen196_pipex_var = ap_uint<1>(0).concat((ap_uint<32>)genpstage_EXEC_TRX_LOCAL.alu_op2);
			genpstage_EXEC_TRX_LOCAL = gen196_pipex_var;
		}
		gen197_pipex_var = ap_uint<1>(0);
		gen197_pipex_var = (gen197_pipex_var || gen194_pipex_var);
		gen197_pipex_var = !gen197_pipex_var;
		gen187_cyclix_var = gen197_pipex_var;
		if (gen187_cyclix_var) {
			gen198_pipex_var = genpstage_EXEC_TRX_LOCAL[31];
			gen199_pipex_var = gen198_pipex_var.concat((ap_uint<32>)genpstage_EXEC_TRX_LOCAL.alu_op1);
			genpstage_EXEC_TRX_LOCAL = gen199_pipex_var;
			gen200_pipex_var = genpstage_EXEC_TRX_LOCAL[31];
			gen201_pipex_var = gen200_pipex_var.concat((ap_uint<32>)genpstage_EXEC_TRX_LOCAL.alu_op2);
			genpstage_EXEC_TRX_LOCAL = gen201_pipex_var;
		}
		gen202_pipex_var = genpsticky_glbl_MIRQEN;
		gen188_cyclix_var = gen202_pipex_var;
		if (gen188_cyclix_var) {
			gen203_pipex_var = ~genpstage_EXEC_TRX_LOCAL.irq_recv;
			gen204_pipex_var = gen203_pipex_var;
			gen189_cyclix_var = gen204_pipex_var;
			if (gen189_cyclix_var) {
				gen190_cyclix_var = genpstage_EXEC_genctrl_active;
				if (gen190_cyclix_var) {
					gen191_cyclix_var = irq_fifo.read_nb(genpstage_EXEC_TRX_LOCAL);
					gen205_pipex_var = gen191_cyclix_var;
				}
				genpstage_EXEC_TRX_LOCAL = gen205_pipex_var;
				gen192_cyclix_var = genpstage_EXEC_genctrl_active;
				if (gen192_cyclix_var) {
					genpstage_EXEC_TRX_BUF = gen205_pipex_var;
				}
				genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.irq_mcause;
				gen193_cyclix_var = genpstage_EXEC_genctrl_active;
				if (gen193_cyclix_var) {
					genpstage_EXEC_TRX_BUF = genpstage_EXEC_TRX_LOCAL.irq_mcause;
				}
			}
			gen206_pipex_var = genpstage_EXEC_TRX_LOCAL.irq_recv;
			gen194_cyclix_var = gen206_pipex_var;
			if (gen194_cyclix_var) {
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(128);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
				gen195_cyclix_var = genpstage_EXEC_genctrl_active;
				if (gen195_cyclix_var) {
					genpsticky_glbl_MIRQEN = ap_uint<32>(0);
				}
				gen196_cyclix_var = genpstage_EXEC_genctrl_active;
				if (gen196_cyclix_var) {
					genpsticky_glbl_CSR_MCAUSE = genpstage_EXEC_TRX_LOCAL.irq_mcause;
				}
				gen197_cyclix_var = genpstage_EXEC_genctrl_active;
				if (gen197_cyclix_var) {
					genpsticky_glbl_MRETADDR = genpstage_EXEC_TRX_LOCAL.curinstr_addr;
				}
			}
		}
		gen207_pipex_var = genpstage_EXEC_TRX_LOCAL.mret_req;
		gen198_cyclix_var = gen207_pipex_var;
		if (gen198_cyclix_var) {
			gen199_cyclix_var = genpstage_EXEC_genctrl_active;
			if (gen199_cyclix_var) {
				genpsticky_glbl_MIRQEN = ap_uint<32>(1);
			}
		}
		genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.alu_op1_wide;
		gen208_pipex_var = genpstage_EXEC_TRX_LOCAL.alu_req;
		gen200_cyclix_var = gen208_pipex_var;
		if (gen200_cyclix_var) {
			switch (genpstage_EXEC_TRX_LOCAL) {
				case 0:
					gen209_pipex_var = (genpstage_EXEC_TRX_LOCAL.alu_op1_wide + genpstage_EXEC_TRX_LOCAL.alu_op2_wide);
					genpstage_EXEC_TRX_LOCAL = gen209_pipex_var;
					break;
				case 1:
					gen210_pipex_var = (genpstage_EXEC_TRX_LOCAL.alu_op1_wide - genpstage_EXEC_TRX_LOCAL.alu_op2_wide);
					genpstage_EXEC_TRX_LOCAL = gen210_pipex_var;
					break;
				case 2:
					gen211_pipex_var = (genpstage_EXEC_TRX_LOCAL.alu_op1_wide & genpstage_EXEC_TRX_LOCAL.alu_op2_wide);
					genpstage_EXEC_TRX_LOCAL = gen211_pipex_var;
					break;
				case 3:
					gen212_pipex_var = (genpstage_EXEC_TRX_LOCAL.alu_op1_wide | genpstage_EXEC_TRX_LOCAL.alu_op2_wide);
					genpstage_EXEC_TRX_LOCAL = gen212_pipex_var;
					break;
				case 4:
					gen213_pipex_var = (genpstage_EXEC_TRX_LOCAL.alu_op1_wide << genpstage_EXEC_TRX_LOCAL.alu_op2_wide);
					genpstage_EXEC_TRX_LOCAL = gen213_pipex_var;
					break;
				case 5:
					gen214_pipex_var = ap_uint<32>(0).concat((ap_uint<32>)genpstage_EXEC_TRX_LOCAL.alu_op1_wide[31:0]);
					gen215_pipex_var = (gen214_pipex_var >> genpstage_EXEC_TRX_LOCAL.alu_op2_wide[4:0]);
					genpstage_EXEC_TRX_LOCAL = gen215_pipex_var;
					break;
				case 6:
					gen216_pipex_var = genpstage_EXEC_TRX_LOCAL.alu_op1_wide[31:0];
					gen217_pipex_var = gen216_pipex_var[31];
					gen218_pipex_var = gen217_pipex_var.concat((ap_uint<63>)gen217_pipex_var.concat((ap_uint<62>)gen217_pipex_var.concat((ap_uint<61>)gen217_pipex_var.concat((ap_uint<60>)gen217_pipex_var.concat((ap_uint<59>)gen217_pipex_var.concat((ap_uint<58>)gen217_pipex_var.concat((ap_uint<57>)gen217_pipex_var.concat((ap_uint<56>)gen217_pipex_var.concat((ap_uint<55>)gen217_pipex_var.concat((ap_uint<54>)gen217_pipex_var.concat((ap_uint<53>)gen217_pipex_var.concat((ap_uint<52>)gen217_pipex_var.concat((ap_uint<51>)gen217_pipex_var.concat((ap_uint<50>)gen217_pipex_var.concat((ap_uint<49>)gen217_pipex_var.concat((ap_uint<48>)gen217_pipex_var.concat((ap_uint<47>)gen217_pipex_var.concat((ap_uint<46>)gen217_pipex_var.concat((ap_uint<45>)gen217_pipex_var.concat((ap_uint<44>)gen217_pipex_var.concat((ap_uint<43>)gen217_pipex_var.concat((ap_uint<42>)gen217_pipex_var.concat((ap_uint<41>)gen217_pipex_var.concat((ap_uint<40>)gen217_pipex_var.concat((ap_uint<39>)gen217_pipex_var.concat((ap_uint<38>)gen217_pipex_var.concat((ap_uint<37>)gen217_pipex_var.concat((ap_uint<36>)gen217_pipex_var.concat((ap_uint<35>)gen217_pipex_var.concat((ap_uint<34>)gen217_pipex_var.concat((ap_uint<33>)gen217_pipex_var.concat((ap_uint<32>)genpstage_EXEC_TRX_LOCAL.alu_op1_wide[31:0]))))))))))))))))))))))))))))))));
					gen219_pipex_var = (gen218_pipex_var >> genpstage_EXEC_TRX_LOCAL.alu_op2_wide[4:0]);
					genpstage_EXEC_TRX_LOCAL = gen219_pipex_var;
					break;
				case 7:
					gen220_pipex_var = (genpstage_EXEC_TRX_LOCAL.alu_op1_wide ^ genpstage_EXEC_TRX_LOCAL.alu_op2_wide);
					genpstage_EXEC_TRX_LOCAL = gen220_pipex_var;
					break;
				case 8:
					gen221_pipex_var = ~genpstage_EXEC_TRX_LOCAL.alu_op2_wide;
					gen222_pipex_var = (genpstage_EXEC_TRX_LOCAL.alu_op1_wide & gen221_pipex_var);
					genpstage_EXEC_TRX_LOCAL = gen222_pipex_var;
					break;
			}
			genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.alu_result_wide[31:0];
			genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.alu_result_wide[32];
			genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.alu_result_wide[31];
			gen223_pipex_var = |genpstage_EXEC_TRX_LOCAL.alu_result;
			gen224_pipex_var = ~gen223_pipex_var;
			genpstage_EXEC_TRX_LOCAL = gen224_pipex_var;
			gen225_pipex_var = ~genpstage_EXEC_TRX_LOCAL.alu_op1[31];
			gen226_pipex_var = ~genpstage_EXEC_TRX_LOCAL.alu_op2[31];
			gen227_pipex_var = (gen225_pipex_var & gen226_pipex_var);
			gen228_pipex_var = (gen227_pipex_var & genpstage_EXEC_TRX_LOCAL.alu_result[31]);
			gen229_pipex_var = ~genpstage_EXEC_TRX_LOCAL.alu_result[31];
			gen230_pipex_var = (genpstage_EXEC_TRX_LOCAL.alu_op1[31] & genpstage_EXEC_TRX_LOCAL.alu_op2[31]);
			gen231_pipex_var = (gen230_pipex_var & gen229_pipex_var);
			gen232_pipex_var = (gen228_pipex_var | gen231_pipex_var);
			genpstage_EXEC_TRX_LOCAL = gen232_pipex_var;
			gen233_pipex_var = genpstage_EXEC_TRX_LOCAL.alu_unsigned;
			gen201_cyclix_var = gen233_pipex_var;
			if (gen201_cyclix_var) {
				genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.alu_CF;
			}
			gen234_pipex_var = ap_uint<1>(0);
			gen234_pipex_var = (gen234_pipex_var || gen233_pipex_var);
			gen234_pipex_var = !gen234_pipex_var;
			gen202_cyclix_var = gen234_pipex_var;
			if (gen202_cyclix_var) {
				genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.alu_OF;
			}
		}
		switch (genpstage_EXEC_TRX_LOCAL) {
			case 0:
				genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.immediate;
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				break;
			case 1:
				genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.alu_result;
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				break;
			case 2:
				genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.alu_CF;
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				break;
			case 3:
				genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.alu_OF;
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				break;
			case 4:
				genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.nextinstr_addr;
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				break;
			case 6:
				genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.csr_rdata;
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				break;
		}
		gen235_pipex_var = (genpstage_EXEC_TRX_LOCAL.curinstr_addr + genpstage_EXEC_TRX_LOCAL.immediate);
		genpstage_EXEC_TRX_LOCAL = gen235_pipex_var;
		switch (genpstage_EXEC_TRX_LOCAL) {
			case 0:
				genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.immediate;
				break;
			case 1:
				genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.alu_result;
				break;
		}
		gen236_pipex_var = genpstage_EXEC_TRX_LOCAL.jump_req_cond;
		gen203_cyclix_var = gen236_pipex_var;
		if (gen203_cyclix_var) {
			switch (genpstage_EXEC_TRX_LOCAL) {
				case 0:
					gen237_pipex_var = genpstage_EXEC_TRX_LOCAL.alu_ZF;
					gen204_cyclix_var = gen237_pipex_var;
					if (gen204_cyclix_var) {
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.curinstraddr_imm;
					}
					break;
				case 1:
					gen238_pipex_var = ~genpstage_EXEC_TRX_LOCAL.alu_ZF;
					gen239_pipex_var = gen238_pipex_var;
					gen205_cyclix_var = gen239_pipex_var;
					if (gen205_cyclix_var) {
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.curinstraddr_imm;
					}
					break;
				case 4:
					gen240_pipex_var = genpstage_EXEC_TRX_LOCAL.alu_CF;
					gen206_cyclix_var = gen240_pipex_var;
					if (gen206_cyclix_var) {
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.curinstraddr_imm;
					}
					break;
				case 5:
					gen241_pipex_var = ~genpstage_EXEC_TRX_LOCAL.alu_CF;
					gen242_pipex_var = gen241_pipex_var;
					gen207_cyclix_var = gen242_pipex_var;
					if (gen207_cyclix_var) {
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.curinstraddr_imm;
					}
					break;
				case 6:
					gen243_pipex_var = genpstage_EXEC_TRX_LOCAL.alu_CF;
					gen208_cyclix_var = gen243_pipex_var;
					if (gen208_cyclix_var) {
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.curinstraddr_imm;
					}
					break;
				case 7:
					gen244_pipex_var = ~genpstage_EXEC_TRX_LOCAL.alu_CF;
					gen245_pipex_var = gen244_pipex_var;
					gen209_cyclix_var = gen245_pipex_var;
					if (gen209_cyclix_var) {
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.curinstraddr_imm;
					}
					break;
			}
		}
		genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.alu_result;
		genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.rs2_rdata;
		gen246_pipex_var = ~genpstage_EXEC_TRX_LOCAL.jump_req_done;
		gen247_pipex_var = gen246_pipex_var;
		gen210_cyclix_var = gen247_pipex_var;
		if (gen210_cyclix_var) {
			gen211_cyclix_var = genpstage_EXEC_genctrl_active;
			if (gen211_cyclix_var) {
				genpsticky_glbl_jump_req_cmd = genpstage_EXEC_TRX_LOCAL.jump_req;
			}
			gen212_cyclix_var = genpstage_EXEC_genctrl_active;
			if (gen212_cyclix_var) {
				genpsticky_glbl_jump_vector_cmd = genpstage_EXEC_TRX_LOCAL.jump_vector;
			}
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
			gen213_cyclix_var = genpstage_EXEC_genctrl_active;
			if (gen213_cyclix_var) {
				genpstage_EXEC_TRX_BUF = ap_uint<32>(1);
			}
		}
		gen248_pipex_var = genpstage_EXEC_TRX_LOCAL.mem_req;
		gen214_cyclix_var = gen248_pipex_var;
		if (gen214_cyclix_var) {
			gen249_pipex_var = ~genpstage_EXEC_TRX_LOCAL.data_req_done;
			gen250_pipex_var = gen249_pipex_var;
			gen215_cyclix_var = gen250_pipex_var;
			if (gen215_cyclix_var) {
				genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.mem_addr;
				genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.mem_be;
				genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.mem_wdata;
				gen216_cyclix_var = genpstage_EXEC_genctrl_active;
				if (gen216_cyclix_var) {
					gen217_cyclix_var = ~genmcopipe_data_mem_full_flag;
					gen218_cyclix_var = gen217_cyclix_var;
					if (gen218_cyclix_var) {
						gen282_pipex_req_struct = genpstage_EXEC_TRX_LOCAL.mem_cmd;
						gen282_pipex_req_struct = genpstage_EXEC_TRX_LOCAL.data_busreq;
						gen219_cyclix_var = genmcopipe_data_mem_req.write_nb(gen282_pipex_req_struct);
						gen220_cyclix_var = gen219_cyclix_var;
						if (gen220_cyclix_var) {
							gen251_pipex_var = ap_uint<32>(1);
							gen221_cyclix_var = !genpstage_EXEC_TRX_LOCAL.mem_cmd;
							genpstage_EXEC_TRX_BUF = gen221_cyclix_var;
							genpstage_EXEC_TRX_BUF = genmcopipe_data_mem_wr_ptr;
							genpstage_EXEC_TRX_BUF = ap_uint<1>(0);
							gen222_cyclix_var = genpstage_EXEC_TRX_BUF[0].genmcopipe_handle_data_mem.rdreq_pending;
							if (gen222_cyclix_var) {
								genmcopipe_data_mem_wr_done = ap_uint<32>(1);
							}
						}
					}
				}
				genpstage_EXEC_TRX_LOCAL = gen251_pipex_var;
				gen223_cyclix_var = genpstage_EXEC_genctrl_active;
				if (gen223_cyclix_var) {
					genpstage_EXEC_TRX_BUF = gen251_pipex_var;
				}
			}
			gen252_pipex_var = ~genpstage_EXEC_TRX_LOCAL.data_req_done;
			gen253_pipex_var = gen252_pipex_var;
			gen224_cyclix_var = gen253_pipex_var;
			if (gen224_cyclix_var) {
				gen225_cyclix_var = genpstage_EXEC_genctrl_active;
				if (gen225_cyclix_var) {
					genpstage_EXEC_genctrl_stalled_glbl = ap_uint<32>(1);
				}
				genpstage_EXEC_genctrl_active = ap_uint<32>(0);
			}
		}
		gen254_pipex_var = genpstage_EXEC_TRX_LOCAL.mem_req;
		gen226_cyclix_var = gen254_pipex_var;
		if (gen226_cyclix_var) {
			gen255_pipex_var = ~genpstage_EXEC_TRX_LOCAL.mem_cmd;
			gen256_pipex_var = gen255_pipex_var;
			gen227_cyclix_var = gen256_pipex_var;
			if (gen227_cyclix_var) {
				gen228_cyclix_var = genpstage_EXEC_TRX_BUF[0].genmcopipe_handle_data_mem.resp_done;
				if (gen228_cyclix_var) {
					genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_BUF[0].genmcopipe_handle_data_mem.rdata;
				}
				gen257_pipex_var = genpstage_EXEC_TRX_BUF[0].genmcopipe_handle_data_mem.resp_done;
				gen258_pipex_var = gen257_pipex_var;
				gen229_cyclix_var = gen258_pipex_var;
				if (gen229_cyclix_var) {
					genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				}
				gen259_pipex_var = ap_uint<1>(0);
				gen259_pipex_var = (gen259_pipex_var || gen258_pipex_var);
				gen259_pipex_var = !gen259_pipex_var;
				gen230_cyclix_var = gen259_pipex_var;
				if (gen230_cyclix_var) {
					gen231_cyclix_var = genpstage_EXEC_genctrl_active;
					if (gen231_cyclix_var) {
						genpstage_EXEC_genctrl_stalled_glbl = ap_uint<32>(1);
					}
					genpstage_EXEC_genctrl_active = ap_uint<32>(0);
				}
			}
		}
		gen260_pipex_var = (genpstage_EXEC_TRX_LOCAL.mem_be == ap_uint<32>(1));
		gen261_pipex_var = gen260_pipex_var;
		gen232_cyclix_var = gen261_pipex_var;
		if (gen232_cyclix_var) {
			gen262_pipex_var = genpstage_EXEC_TRX_LOCAL.load_signext;
			gen233_cyclix_var = gen262_pipex_var;
			if (gen233_cyclix_var) {
				gen263_pipex_var = genpstage_EXEC_TRX_LOCAL.mem_rdata[7:0];
				gen264_pipex_var = gen263_pipex_var[7];
				gen265_pipex_var = gen264_pipex_var.concat((ap_uint<31>)gen264_pipex_var.concat((ap_uint<30>)gen264_pipex_var.concat((ap_uint<29>)gen264_pipex_var.concat((ap_uint<28>)gen264_pipex_var.concat((ap_uint<27>)gen264_pipex_var.concat((ap_uint<26>)gen264_pipex_var.concat((ap_uint<25>)gen264_pipex_var.concat((ap_uint<24>)gen264_pipex_var.concat((ap_uint<23>)gen264_pipex_var.concat((ap_uint<22>)gen264_pipex_var.concat((ap_uint<21>)gen264_pipex_var.concat((ap_uint<20>)gen264_pipex_var.concat((ap_uint<19>)gen264_pipex_var.concat((ap_uint<18>)gen264_pipex_var.concat((ap_uint<17>)gen264_pipex_var.concat((ap_uint<16>)gen264_pipex_var.concat((ap_uint<15>)gen264_pipex_var.concat((ap_uint<14>)gen264_pipex_var.concat((ap_uint<13>)gen264_pipex_var.concat((ap_uint<12>)gen264_pipex_var.concat((ap_uint<11>)gen264_pipex_var.concat((ap_uint<10>)gen264_pipex_var.concat((ap_uint<9>)gen264_pipex_var.concat((ap_uint<8>)genpstage_EXEC_TRX_LOCAL.mem_rdata[7:0]))))))))))))))))))))))));
				genpstage_EXEC_TRX_LOCAL = gen265_pipex_var;
			}
			gen266_pipex_var = ap_uint<1>(0);
			gen266_pipex_var = (gen266_pipex_var || gen262_pipex_var);
			gen266_pipex_var = !gen266_pipex_var;
			gen234_cyclix_var = gen266_pipex_var;
			if (gen234_cyclix_var) {
				gen267_pipex_var = ap_uint<24>(0).concat((ap_uint<8>)genpstage_EXEC_TRX_LOCAL.mem_rdata[7:0]);
				genpstage_EXEC_TRX_LOCAL = gen267_pipex_var;
			}
		}
		gen268_pipex_var = (genpstage_EXEC_TRX_LOCAL.mem_be == ap_uint<32>(3));
		gen269_pipex_var = gen268_pipex_var;
		gen235_cyclix_var = gen269_pipex_var;
		if (gen235_cyclix_var) {
			gen270_pipex_var = genpstage_EXEC_TRX_LOCAL.load_signext;
			gen236_cyclix_var = gen270_pipex_var;
			if (gen236_cyclix_var) {
				gen271_pipex_var = genpstage_EXEC_TRX_LOCAL.mem_rdata[15:0];
				gen272_pipex_var = gen271_pipex_var[15];
				gen273_pipex_var = gen272_pipex_var.concat((ap_uint<31>)gen272_pipex_var.concat((ap_uint<30>)gen272_pipex_var.concat((ap_uint<29>)gen272_pipex_var.concat((ap_uint<28>)gen272_pipex_var.concat((ap_uint<27>)gen272_pipex_var.concat((ap_uint<26>)gen272_pipex_var.concat((ap_uint<25>)gen272_pipex_var.concat((ap_uint<24>)gen272_pipex_var.concat((ap_uint<23>)gen272_pipex_var.concat((ap_uint<22>)gen272_pipex_var.concat((ap_uint<21>)gen272_pipex_var.concat((ap_uint<20>)gen272_pipex_var.concat((ap_uint<19>)gen272_pipex_var.concat((ap_uint<18>)gen272_pipex_var.concat((ap_uint<17>)gen272_pipex_var.concat((ap_uint<16>)genpstage_EXEC_TRX_LOCAL.mem_rdata[15:0]))))))))))))))));
				genpstage_EXEC_TRX_LOCAL = gen273_pipex_var;
			}
			gen274_pipex_var = ap_uint<1>(0);
			gen274_pipex_var = (gen274_pipex_var || gen270_pipex_var);
			gen274_pipex_var = !gen274_pipex_var;
			gen237_cyclix_var = gen274_pipex_var;
			if (gen237_cyclix_var) {
				gen275_pipex_var = ap_uint<16>(0).concat((ap_uint<16>)genpstage_EXEC_TRX_LOCAL.mem_rdata[15:0]);
				genpstage_EXEC_TRX_LOCAL = gen275_pipex_var;
			}
		}
		gen276_pipex_var = (genpstage_EXEC_TRX_LOCAL.rd_source == ap_uint<32>(5));
		gen277_pipex_var = gen276_pipex_var;
		gen238_cyclix_var = gen277_pipex_var;
		if (gen238_cyclix_var) {
			genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.mem_rdata;
		}
		gen278_pipex_var = (genpstage_EXEC_TRX_LOCAL.rd_req && genpstage_EXEC_TRX_LOCAL.rd_rdy);
		gen279_pipex_var = gen278_pipex_var;
		gen239_cyclix_var = gen279_pipex_var;
		if (gen239_cyclix_var) {
			genpsticky_glbl_regfile = genpstage_EXEC_TRX_LOCAL.rd_wdata;
		}
		// Processing of next pstage busyness
		// pctrl_finish and pctrl_succ formation
		gen240_cyclix_var = genpstage_EXEC_genctrl_stalled_glbl;
		if (gen240_cyclix_var) {
			genpstage_EXEC_genctrl_finish = ap_uint<32>(0);
			genpstage_EXEC_genctrl_succ = ap_uint<32>(0);
		}
		gen241_cyclix_var = ap_uint<1>(0);
		gen241_cyclix_var = (gen241_cyclix_var || gen240_cyclix_var);
		gen241_cyclix_var = !gen241_cyclix_var;
		if (gen241_cyclix_var) {
			genpstage_EXEC_genctrl_finish = genpstage_EXEC_genctrl_occupied;
			genpstage_EXEC_genctrl_succ = genpstage_EXEC_genctrl_active;
		}
		// credit counter processing
		// asserting succ signals
		// processing context in case transaction is ready to propagate
		gen242_cyclix_var = genpstage_EXEC_genctrl_finish;
		if (gen242_cyclix_var) {
			// programming next stage in case transaction is able to propagate
			gen243_cyclix_var = genpstage_EXEC_genctrl_succ;
			if (gen243_cyclix_var) {
			}
			genpstage_EXEC_genctrl_stalled_glbl = ap_uint<32>(0);
			genpstage_EXEC_genctrl_active = ap_uint<32>(0);
			genpstage_EXEC_TRX_BUF = '{default:ap_uint<32>(0)};
			genpstage_EXEC_TRX_BUF_COUNTER_FULL = ap_uint<32>(0);
			genpstage_EXEC_TRX_BUF_COUNTER_NEMPTY = ap_uint<32>(0);
			genpstage_EXEC_TRX_BUF_COUNTER = (genpstage_EXEC_TRX_BUF_COUNTER - ap_uint<32>(1));
		}
		gen244_cyclix_var = ~genpstage_EXEC_TRX_BUF_COUNTER_FULL;
		genpstage_EXEC_genctrl_rdy = gen244_cyclix_var;
		genpstage_EXEC_genctrl_working = (genpstage_EXEC_genctrl_succ | genpstage_EXEC_genctrl_stalled_glbl);
		// #### Stage processing: IFETCH ####
		genpstage_IFETCH_genctrl_succ = ap_uint<32>(0);
		genpstage_IFETCH_genctrl_working = ap_uint<32>(0);
		gen245_cyclix_var = genpstage_IFETCH_genctrl_stalled_glbl;
		if (gen245_cyclix_var) {
			genpstage_IFETCH_genctrl_new = ap_uint<32>(0);
			genpstage_IFETCH_genctrl_stalled_glbl = ap_uint<32>(0);
			genpstage_IFETCH_genctrl_active = ap_uint<32>(1);
		}
		gen246_cyclix_var = ap_uint<1>(0);
		gen246_cyclix_var = (gen246_cyclix_var || gen245_cyclix_var);
		gen246_cyclix_var = !gen246_cyclix_var;
		if (gen246_cyclix_var) {
			genpstage_IFETCH_genctrl_active = ap_uint<32>(1);
			genpstage_IFETCH_genctrl_new = genpstage_IFETCH_genctrl_active;
		}
		genpstage_IFETCH_genctrl_occupied = genpstage_IFETCH_genctrl_active;
		genpstage_IFETCH_genctrl_finish = ap_uint<32>(0);
		genpstage_IFETCH_genpctrl_flushreq = ap_uint<32>(0);
		genpstage_IFETCH_genpctrl_flushreq = (genpstage_IFETCH_genpctrl_flushreq | genpstage_EXEC_genpctrl_flushreq);
		gen247_cyclix_var = genpstage_IFETCH_genctrl_occupied;
		if (gen247_cyclix_var) {
			// Initializing new newaccums descriptors ####
			gen248_cyclix_var = genpstage_IFETCH_genctrl_new;
			if (gen248_cyclix_var) {
				genpstage_IFETCH_TRX_BUF = ap_uint<32>(0);
			}
			// Fetching locals from src_glbls
			genpstage_IFETCH_TRX_LOCAL = ap_uint<32>(0);
			genpstage_IFETCH_TRX_LOCAL = ap_uint<32>(0);
			genpstage_IFETCH_TRX_LOCAL = genpstage_IFETCH_TRX_BUF[0].instr_req_done;
			genpstage_IFETCH_TRX_LOCAL = '{default:ap_uint<32>(0)};
			// Acquiring mcopipe rdata
			gen249_cyclix_var = genpstage_IFETCH_TRX_BUF[0].genmcopipe_handle_instr_mem.rdreq_pending;
			if (gen249_cyclix_var) {
				gen250_cyclix_var = (genpstage_IFETCH_TRX_BUF[0].genmcopipe_handle_instr_mem.if_id == ap_uint<1>(0));
				gen251_cyclix_var = gen250_cyclix_var;
				if (gen251_cyclix_var) {
					gen252_cyclix_var = (genpstage_IFETCH_TRX_BUF[0].genmcopipe_handle_instr_mem.tid == genmcopipe_instr_mem_rd_ptr);
					gen253_cyclix_var = gen252_cyclix_var;
					if (gen253_cyclix_var) {
						gen254_cyclix_var = genmcopipe_instr_mem_resp.read_nb(gen283_pipex_mcopipe_rdata);
						gen255_cyclix_var = gen254_cyclix_var;
						if (gen255_cyclix_var) {
							genpstage_IFETCH_TRX_BUF = ap_uint<32>(0);
							genpstage_IFETCH_TRX_BUF = ap_uint<32>(1);
							genpstage_IFETCH_TRX_BUF = gen283_pipex_mcopipe_rdata;
							genmcopipe_instr_mem_rd_done = ap_uint<32>(1);
						}
					}
				}
			}
			// Pipeline flush processing
			gen256_cyclix_var = genpstage_IFETCH_genpctrl_flushreq;
			if (gen256_cyclix_var) {
			}
		}
		// Saving succ targets
		gen140_pipex_succbuf = genpsticky_glbl_pc;
		// Generating payload
		gen141_pipex_var = genpsticky_glbl_jump_req_cmd;
		gen257_cyclix_var = gen141_pipex_var;
		if (gen257_cyclix_var) {
			gen258_cyclix_var = genpstage_IFETCH_genctrl_active;
			if (gen258_cyclix_var) {
				genpsticky_glbl_pc = genpsticky_glbl_jump_vector_cmd;
			}
			gen259_cyclix_var = genpstage_IFETCH_genctrl_active;
			if (gen259_cyclix_var) {
				genpsticky_glbl_jump_req_cmd = ap_uint<32>(0);
			}
		}
		genpstage_IFETCH_TRX_LOCAL = genpsticky_glbl_pc;
		gen142_pipex_var = (genpstage_IFETCH_TRX_LOCAL.curinstr_addr + ap_uint<32>(4));
		genpstage_IFETCH_TRX_LOCAL = gen142_pipex_var;
		gen139_pipex_succreq = ap_uint<32>(1);
		gen140_pipex_succbuf = genpstage_IFETCH_TRX_LOCAL.nextinstr_addr;
		gen143_pipex_var = genpsticky_glbl_jump_req_cmd;
		gen260_cyclix_var = gen143_pipex_var;
		if (gen260_cyclix_var) {
			genpstage_IFETCH_TRX_LOCAL = ap_uint<32>(0);
			gen261_cyclix_var = genpstage_IFETCH_genctrl_active;
			if (gen261_cyclix_var) {
				genpstage_IFETCH_TRX_BUF = ap_uint<32>(0);
			}
		}
		genpstage_IFETCH_TRX_LOCAL = genpstage_IFETCH_TRX_LOCAL.curinstr_addr;
		genpstage_IFETCH_TRX_LOCAL = ap_uint<32>(15);
		genpstage_IFETCH_TRX_LOCAL = ap_uint<32>(0);
		gen144_pipex_var = ~genpstage_IFETCH_TRX_LOCAL.instr_req_done;
		gen145_pipex_var = gen144_pipex_var;
		gen262_cyclix_var = gen145_pipex_var;
		if (gen262_cyclix_var) {
			gen263_cyclix_var = genpstage_IFETCH_genctrl_active;
			if (gen263_cyclix_var) {
				gen264_cyclix_var = ~genmcopipe_instr_mem_full_flag;
				gen265_cyclix_var = gen264_cyclix_var;
				if (gen265_cyclix_var) {
					gen284_pipex_req_struct = ap_uint<1>(0);
					gen284_pipex_req_struct = genpstage_IFETCH_TRX_LOCAL.instr_busreq;
					gen266_cyclix_var = genmcopipe_instr_mem_req.write_nb(gen284_pipex_req_struct);
					gen267_cyclix_var = gen266_cyclix_var;
					if (gen267_cyclix_var) {
						gen146_pipex_var = ap_uint<32>(1);
						gen268_cyclix_var = !ap_uint<1>(0);
						genpstage_IFETCH_TRX_BUF = gen268_cyclix_var;
						genpstage_IFETCH_TRX_BUF = genmcopipe_instr_mem_wr_ptr;
						genpstage_IFETCH_TRX_BUF = ap_uint<1>(0);
						gen269_cyclix_var = genpstage_IFETCH_TRX_BUF[0].genmcopipe_handle_instr_mem.rdreq_pending;
						if (gen269_cyclix_var) {
							genmcopipe_instr_mem_wr_done = ap_uint<32>(1);
						}
					}
				}
			}
			genpstage_IFETCH_TRX_LOCAL = gen146_pipex_var;
			gen270_cyclix_var = genpstage_IFETCH_genctrl_active;
			if (gen270_cyclix_var) {
				genpstage_IFETCH_TRX_BUF = gen146_pipex_var;
			}
		}
		gen147_pipex_var = ~genpstage_IFETCH_TRX_LOCAL.instr_req_done;
		gen148_pipex_var = gen147_pipex_var;
		gen271_cyclix_var = gen148_pipex_var;
		if (gen271_cyclix_var) {
			gen272_cyclix_var = genpstage_IFETCH_genctrl_active;
			if (gen272_cyclix_var) {
				genpstage_IFETCH_genctrl_stalled_glbl = ap_uint<32>(1);
			}
			genpstage_IFETCH_genctrl_active = ap_uint<32>(0);
		}
		// Processing of next pstage busyness
		gen273_cyclix_var = ~genpstage_EXEC_genctrl_rdy;
		gen274_cyclix_var = gen273_cyclix_var;
		if (gen274_cyclix_var) {
			gen275_cyclix_var = genpstage_IFETCH_genctrl_active;
			if (gen275_cyclix_var) {
				genpstage_IFETCH_genctrl_stalled_glbl = ap_uint<32>(1);
			}
			genpstage_IFETCH_genctrl_active = ap_uint<32>(0);
		}
		// pctrl_finish and pctrl_succ formation
		gen276_cyclix_var = genpstage_IFETCH_genctrl_stalled_glbl;
		if (gen276_cyclix_var) {
			genpstage_IFETCH_genctrl_finish = ap_uint<32>(0);
			genpstage_IFETCH_genctrl_succ = ap_uint<32>(0);
		}
		gen277_cyclix_var = ap_uint<1>(0);
		gen277_cyclix_var = (gen277_cyclix_var || gen276_cyclix_var);
		gen277_cyclix_var = !gen277_cyclix_var;
		if (gen277_cyclix_var) {
			genpstage_IFETCH_genctrl_finish = genpstage_IFETCH_genctrl_occupied;
			genpstage_IFETCH_genctrl_succ = genpstage_IFETCH_genctrl_active;
		}
		// credit counter processing
		// asserting succ signals
		gen278_cyclix_var = genpstage_IFETCH_genctrl_succ;
		if (gen278_cyclix_var) {
			gen279_cyclix_var = gen139_pipex_succreq;
			if (gen279_cyclix_var) {
				genpsticky_glbl_pc = gen140_pipex_succbuf;
			}
		}
		// processing context in case transaction is ready to propagate
		gen280_cyclix_var = genpstage_IFETCH_genctrl_finish;
		if (gen280_cyclix_var) {
			// programming next stage in case transaction is able to propagate
			gen281_cyclix_var = genpstage_IFETCH_genctrl_succ;
			if (gen281_cyclix_var) {
				gen282_cyclix_var = genpstage_EXEC_genctrl_rdy;
				if (gen282_cyclix_var) {
					// propagating transaction context
					genpstage_EXEC_push_trx = genpstage_IFETCH_TRX_LOCAL.curinstr_addr;
					genpstage_EXEC_push_trx = genpstage_IFETCH_TRX_LOCAL.nextinstr_addr;
					genpstage_EXEC_push_trx = genpstage_IFETCH_TRX_BUF[0].genmcopipe_handle_instr_mem.if_id;
					genpstage_EXEC_push_trx = genpstage_IFETCH_TRX_BUF[0].genmcopipe_handle_instr_mem.resp_done;
					genpstage_EXEC_push_trx = genpstage_IFETCH_TRX_BUF[0].genmcopipe_handle_instr_mem.rdata;
					genpstage_EXEC_push_trx = genpstage_IFETCH_TRX_BUF[0].genmcopipe_handle_instr_mem.rdreq_pending;
					genpstage_EXEC_push_trx = genpstage_IFETCH_TRX_BUF[0].genmcopipe_handle_instr_mem.tid;
					genpstage_EXEC_TRX_BUF = genpstage_EXEC_push_trx;
					genpstage_EXEC_TRX_BUF_COUNTER_NEMPTY = ap_uint<32>(1);
					genpstage_EXEC_TRX_BUF_COUNTER_FULL = ap_uint<32>(1);
					genpstage_EXEC_TRX_BUF_COUNTER = (genpstage_EXEC_TRX_BUF_COUNTER + ap_uint<32>(1));
				}
			}
			genpstage_IFETCH_genctrl_stalled_glbl = ap_uint<32>(0);
			genpstage_IFETCH_genctrl_active = ap_uint<32>(0);
			genpstage_IFETCH_TRX_BUF = '{default:ap_uint<32>(0)};
			genpstage_IFETCH_TRX_BUF_COUNTER_FULL = ap_uint<32>(0);
			genpstage_IFETCH_TRX_BUF_COUNTER_NEMPTY = ap_uint<32>(0);
			genpstage_IFETCH_TRX_BUF_COUNTER = (genpstage_IFETCH_TRX_BUF_COUNTER - ap_uint<32>(1));
		}
		gen283_cyclix_var = ~genpstage_IFETCH_TRX_BUF_COUNTER_FULL;
		genpstage_IFETCH_genctrl_rdy = gen283_cyclix_var;
		genpstage_IFETCH_genctrl_working = (genpstage_IFETCH_genctrl_succ | genpstage_IFETCH_genctrl_stalled_glbl);
		gen284_cyclix_var = genmcopipe_instr_mem_rd_done;
		if (gen284_cyclix_var) {
			genmcopipe_instr_mem_rd_ptr = genmcopipe_instr_mem_rd_ptr_next;
			genmcopipe_instr_mem_full_flag = ap_uint<32>(0);
			gen285_cyclix_var = (genmcopipe_instr_mem_rd_ptr == genmcopipe_instr_mem_wr_ptr);
			gen286_cyclix_var = gen285_cyclix_var;
			if (gen286_cyclix_var) {
				genmcopipe_instr_mem_empty_flag = ap_uint<32>(1);
			}
		}
		gen287_cyclix_var = genmcopipe_instr_mem_wr_done;
		if (gen287_cyclix_var) {
			genmcopipe_instr_mem_wr_ptr = genmcopipe_instr_mem_wr_ptr_next;
			genmcopipe_instr_mem_empty_flag = ap_uint<32>(0);
			gen288_cyclix_var = (genmcopipe_instr_mem_rd_ptr == genmcopipe_instr_mem_wr_ptr);
			gen289_cyclix_var = gen288_cyclix_var;
			if (gen289_cyclix_var) {
				genmcopipe_instr_mem_full_flag = ap_uint<32>(1);
			}
		}
		gen290_cyclix_var = genmcopipe_data_mem_rd_done;
		if (gen290_cyclix_var) {
			genmcopipe_data_mem_rd_ptr = genmcopipe_data_mem_rd_ptr_next;
			genmcopipe_data_mem_full_flag = ap_uint<32>(0);
			gen291_cyclix_var = (genmcopipe_data_mem_rd_ptr == genmcopipe_data_mem_wr_ptr);
			gen292_cyclix_var = gen291_cyclix_var;
			if (gen292_cyclix_var) {
				genmcopipe_data_mem_empty_flag = ap_uint<32>(1);
			}
		}
		gen293_cyclix_var = genmcopipe_data_mem_wr_done;
		if (gen293_cyclix_var) {
			genmcopipe_data_mem_wr_ptr = genmcopipe_data_mem_wr_ptr_next;
			genmcopipe_data_mem_empty_flag = ap_uint<32>(0);
			gen294_cyclix_var = (genmcopipe_data_mem_rd_ptr == genmcopipe_data_mem_wr_ptr);
			gen295_cyclix_var = gen294_cyclix_var;
			if (gen295_cyclix_var) {
				genmcopipe_data_mem_full_flag = ap_uint<32>(1);
			}
		}
	}
}
